/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnnouncementCategory = { 'HR' : null } |
  { 'IT' : null } |
  { 'General' : null };
export interface AnnouncementPublic {
  'id' : bigint,
  'title' : string,
  'isDeleted' : boolean,
  'imageFile' : [] | [ExternalBlob],
  'authorId' : string,
  'body' : string,
  'authorName' : string,
  'allowDownload' : boolean,
  'datePosted' : Timestamp,
  'category' : AnnouncementCategory,
}
export interface AnnouncementWithPoll {
  'poll' : [] | [PollResult],
  'announcement' : AnnouncementPublic,
}
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'actorName' : string,
  'target' : string,
  'timestamp' : bigint,
  'ipAddress' : string,
}
export type Branch = { 'Bawjiase' : null } |
  { 'KasoaMain' : null } |
  { 'Ofaakor' : null } |
  { 'HeadOffice' : null } |
  { 'Adeiso' : null } |
  { 'KasoaNewMarket' : null };
export interface CreateAnnouncementInput {
  'title' : string,
  'imageFile' : [] | [ExternalBlob],
  'body' : string,
  'authorName' : string,
  'allowDownload' : boolean,
  'category' : AnnouncementCategory,
}
export interface CreateFormInput {
  'title' : string,
  'filename' : string,
  'category' : FormCategory,
}
export interface CreateNotificationInput {
  'title' : string,
  'userId' : UserId,
  'link' : [] | [string],
  'message' : string,
}
export interface CreatePollInput {
  'question' : string,
  'options' : Array<string>,
  'announcementId' : bigint,
}
export type Department = { 'HR' : null } |
  { 'IT' : null } |
  { 'Susu' : null } |
  { 'Compliance' : null } |
  { 'Bawjiase' : null } |
  { 'Recovery' : null } |
  { 'EBanking' : null } |
  { 'KasoaMain' : null } |
  { 'Admin' : null } |
  { 'Credit' : null } |
  { 'Ofaakor' : null } |
  { 'Audit' : null } |
  { 'HeadOffice' : null } |
  { 'Adeiso' : null } |
  { 'KasoaNewMarket' : null } |
  { 'Microfinance' : null } |
  { 'BankingOperations' : null };
export type ExternalBlob = Uint8Array;
export interface Form {
  'id' : bigint,
  'title' : string,
  'filename' : string,
  'category' : FormCategory,
  'uploadDate' : Timestamp,
}
export type FormCategory = { 'HR' : null } |
  { 'IT' : null } |
  { 'General' : null } |
  { 'Operations' : null } |
  { 'Finance' : null };
export interface NotificationPublic {
  'id' : bigint,
  'title' : string,
  'userId' : string,
  'link' : [] | [string],
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export interface Poll {
  'id' : bigint,
  'question' : string,
  'announcementId' : bigint,
}
export interface PollOptionResult {
  'votedByMe' : boolean,
  'optionId' : bigint,
  'voteCount' : bigint,
  'optionText' : string,
}
export interface PollResult {
  'question' : string,
  'options' : Array<PollOptionResult>,
  'pollId' : bigint,
}
export interface RegisterRequest {
  'branch' : Branch,
  'accessCode' : [] | [string],
  'email' : string,
  'fullname' : string,
  'passwordHash' : string,
  'phone' : string,
  'department' : Department,
  'position' : string,
}
export type Role = { 'HRAdmin' : null } |
  { 'GeneralStaff' : null } |
  { 'SuperAdmin' : null };
export interface StaffStats {
  'branchesWithStaff' : bigint,
  'activeCount' : bigint,
  'archivedCount' : bigint,
}
export type Timestamp = bigint;
export interface UpdateAnnouncementInput {
  'id' : bigint,
  'title' : string,
  'imageFile' : [] | [ExternalBlob],
  'body' : string,
  'allowDownload' : boolean,
  'category' : AnnouncementCategory,
}
export interface UpdateFormInput {
  'id' : bigint,
  'title' : string,
  'filename' : string,
  'category' : FormCategory,
}
export interface UpdateProfileRequest {
  'imageFile' : [] | [ExternalBlob],
  'fullname' : [] | [string],
  'phone' : [] | [string],
}
export interface UpdateStaffRequest {
  'branch' : [] | [Branch],
  'role' : [] | [Role],
  'department' : [] | [Department],
  'position' : [] | [string],
}
export interface User {
  'id' : Principal,
  'branch' : Branch,
  'imageFile' : [] | [Uint8Array],
  'role' : Role,
  'isArchived' : boolean,
  'isActive' : boolean,
  'email' : string,
  'fullname' : string,
  'isVerified' : boolean,
  'phone' : string,
  'department' : Department,
  'position' : string,
  'registrationTime' : bigint,
  'lastSeen' : bigint,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'archiveStaff' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPasswordReset' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createAnnouncement' : ActorMethod<
    [CreateAnnouncementInput],
    AnnouncementPublic
  >,
  'createForm' : ActorMethod<[CreateFormInput], Form>,
  'createNotification' : ActorMethod<
    [CreateNotificationInput],
    NotificationPublic
  >,
  'createPoll' : ActorMethod<[CreatePollInput], Poll>,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deleteAuditLog' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteAuditLogs' : ActorMethod<
    [Array<bigint>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteForm' : ActorMethod<[bigint], boolean>,
  'deleteStaff' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActiveStaff' : ActorMethod<[], Array<User>>,
  'getAnnouncements' : ActorMethod<[], Array<AnnouncementWithPoll>>,
  'getArchivedStaff' : ActorMethod<[], Array<User>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getForms' : ActorMethod<[], Array<Form>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getPollResult' : ActorMethod<[bigint], [] | [PollResult]>,
  'getStaffMember' : ActorMethod<[Principal], [] | [User]>,
  'getStaffStats' : ActorMethod<[], StaffStats>,
  'getTrashedAnnouncements' : ActorMethod<[], Array<AnnouncementPublic>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'hideAnnouncement' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logAction' : ActorMethod<[string, string, string, string], undefined>,
  'logAnnouncementDownload' : ActorMethod<[bigint], undefined>,
  'login' : ActorMethod<[string, string], { 'ok' : User } | { 'err' : string }>,
  'logout' : ActorMethod<[], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'permanentDeleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'register' : ActorMethod<
    [RegisterRequest],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'requestPasswordReset' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resendVerificationCode' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'restoreAnnouncement' : ActorMethod<[bigint], boolean>,
  'restoreStaff' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAnnouncement' : ActorMethod<
    [UpdateAnnouncementInput],
    [] | [AnnouncementPublic]
  >,
  'updateForm' : ActorMethod<[UpdateFormInput], [] | [Form]>,
  'updateLastSeen' : ActorMethod<[], undefined>,
  'updateMyProfile' : ActorMethod<
    [UpdateProfileRequest],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'updateStaff' : ActorMethod<
    [Principal, UpdateStaffRequest],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'verifyEmail' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'vote' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];